apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployapp
  labels:
      app: deployapp
spec:
    replicas: 2     #desiredstate
    strategy: 
          type: RollingUpdate
    selector: 
          matchLabels:
            app: deployapp
    template: 
        metadata: 
            labels: 
              app: deployapp   
        spec: 
          containers:
             - name: frontendapp
               image: anupdudhe/frontendrds
               ports:
                  - containerPort: 80
                    protocol: TCP
               resources:
                  requests:
                        memory: "64mi"
                        cpu: "125m"
                  limits:     
                        memory: "128mi"
                        cpu: "250m"

