apiVersion: v1
kind: Pod
metadata: 
      name: myfirstpod
spec:
    containers: 
        - name: ngninxcont 
          image: nginx:latest
          resources: 
            requests:
              cpu: "500m"
              memory: "128Mi" 
          ports: 
              - containerPort: 8080
                name: http
                protocol: TCP 