apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
  name: rs
  labels:
    app: new-app
spec:
    selector: 
      matchExpressions:      
       #-  { key: app, operator: In , values: [rsapp,  new-app]}
        -  { key: app, operator: Exists , values: [new-app]}
    #matchLabels: 
          #app: rsapp
    replicas: 4
    template:
      metadata:
        labels:
          name: nginxapp
          app: new-app
      spec:
        containers:
          - name: nginxapp
            image: nginx:latest 
            ports:
                - containerPort: 80
                  protocol: TCP
